### ISSUE TITLE
Merge Explore and Focus tabs

### ISSUE THREAD

**Issue by AlmightyYakob** [girder/Danesfield#28]
- [x] Move all content from Focus to Explore (#29)
- [x] Sidebar in Explore tab would show datasets, and upon click, would show that dataset's files, with the ability to navigate back to the first view. (#29)
- [x] Only display files within a particular dataset (blocked on https://github.com/ResonantGeoData/RD-OASIS/issues/32) (#30)

**Comment by mvandenburgh** [comment]
This is done.
